### ISSUE TITLE
Deploy application on Heroku

### ISSUE THREAD

**Issue by mr-jestin-roy** [mr-jestin-roy/neeto-ui-challenge#6]

**Comment by mr-jestin-roy** [comment]
Deployed on https://mr-jestin-roy-neeto-ui.herokuapp.com/

Login Details :
Username: [oliver@example.com](mailto:oliver@example.com)
Password: welcome

**Comment by yedhink** [comment]
@mr-jestin-roy

- [x] No validation is triggered even if the email I have entered is not of a valid email format:
<img width="467" alt="image" src="https://user-images.githubusercontent.com/31244999/190167653-b7ab9814-d844-45a3-8fac-36631ac60634.png">

Rest LGTM. Once you fix this issue, you can mark this challenge as completed and go ahead with the next task.
